-   id: coverage-pre-commit
    name: coverage
    description: A pre-commit hook to check coverage on your code.
    entry: coverage_pre_commit
    language: python
    always_run: true
    require_serial: true
    fail_fast: true
    pass_filenames: false
    stages: [pre-commit, pre-push, manual]
    args: [--fail-under=80]
