name: Question
description: Ask a question about coverage-pre-commit
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true

  - type: input
    attributes:
      label: Platform
      description: What operating system and architecture are you using? (see `uname -orsm`)
      placeholder: e.g., macOS 14 arm64, Windows 11 x86_64, Ubuntu 20.04 amd64
    validations:
      required: false

  - type: input
    attributes:
      label: Version
      description: What version of coverage-pre-commit are you using? (see `coverage_pre_commit version`)
      placeholder: e.g., coverage-pre-commit 0.1.0
    validations:
      required: false
